#!/usr/bin/env python

import hashlib
import fileinput
import sys

def usage_error(msg = None):
	if msg:
		print >>sys.stderr, msg
	print >>sys.stderr, sys.argv[0], "[ <fasta file> ]*"
	print >>sys.stderr, "cat <fasta file> | ", sys.argv[0]

if len(sys.argv) != 2:
	usage_error()

currentSequence = None
hasher = None

for line in fileinput.input():
	line = line.rstrip()
	if line.startswith(">"):
		if currentSequence:
			print "%s\t%s" % (currentSequence, hasher.hexdigest())
		currentSequence = line.lstrip("> ")
		hasher = hashlib.md5()
	else:
		if line: # if line not empty
			hasher.update(line)

if currentSequence:
	print "%s\t%s" % (currentSequence, hasher.hexdigest())
