#!/usr/bin/python

import sys
import os
import logging
from pydoop.mapreduce.simulator import HadoopSimulatorNetwork

def generate_pipes_code(module_name):
    executable = '/usr/bin/python'
    lines = []
    lines.append("#!/bin/bash")
    lines.append('""":"')
    lines.append('exec "%s" -u "$0" "$@"' % executable)
    lines.append('":"""')
    lines.append('import %s as module' % module_name)
    lines.append('module.__main__()')
    return os.linesep.join(lines) + os.linesep


def main():
    log_level = logging.INFO
    logger = logging.getLogger('simulator')
    logger.setLevel(log_level)
    module_name, data_in, data_out = sys.argv[1:]
    program_name = './foo'
    conf = {
        "mapred.reduce.tasks": "1",
    }
    with open(program_name, 'w') as p:
        p.write(generate_pipes_code(module_name))
    os.chmod(program_name, 0x1c0)
    hs = HadoopSimulatorNetwork(program=program_name, logger=logger,
                                loglevel=log_level)
    logger.info('running %s on %s -> %s', module_name, data_in, data_out)
    hs.run(open(data_in), open(data_out, 'w'), conf)


main()

